<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-24 at 15:04:55.
 */
class CombinationStatisticsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CombinationStatistics
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CombinationStatistics;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers CombinationStatistics::populateStats
     * @todo   Implement testPopulateStats().
     */
    public function testPopulateStats()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::find_cRd
     * @todo   Implement testFind_cRd().
     */
    public function testFind_cRd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::find_cRf
     * @todo   Implement testFind_cRf().
     */
    public function testFind_cRf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::find_RcRf
     * @todo   Implement testFind_RcRf().
     */
    public function testFind_RcRf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::find_cDd
     * @todo   Implement testFind_cDd().
     */
    public function testFind_cDd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::find_cDf
     * @todo   Implement testFind_cDf().
     */
    public function testFind_cDf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::cRd_cRf
     * @todo   Implement testCRd_cRf().
     */
    public function testCRd_cRf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::print_cDd
     * @todo   Implement testPrint_cDd().
     */
    public function testPrint_cDd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::print_cDf
     * @todo   Implement testPrint_cDf().
     */
    public function testPrint_cDf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationStatistics::find_foe
     * @todo   Implement testFind_foe().
     */
    public function testFind_foe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
