<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-24 at 15:02:42.
 */
class CombinationGeneratorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CombinationGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CombinationGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers CombinationGenerator::rule_a1
     * @todo   Implement testRule_a1().
     */
    public function testRule_a1()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationGenerator::rule_a2
     * @todo   Implement testRule_a2().
     */
    public function testRule_a2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationGenerator::rule_a3
     * @todo   Implement testRule_a3().
     */
    public function testRule_a3()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationGenerator::rule_a4
     * @todo   Implement testRule_a4().
     */
    public function testRule_a4()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CombinationGenerator::rule_a5
     * @todo   Implement testRule_a5().
     */
    public function testRule_a5()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
